version: "3.9"

services:
  web:
    build:
      context: ./web
    container_name: web
    volumes:
      - ./web:/app

  api:
    build: ./api
    container_name: api
    depends_on:
      - db
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.dev
  
  nginx:
    image: nginx:1.24-alpine
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
      - "8000:80"
    depends_on:
      - api

  db:
    image: postgres:16.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=app_passkey
      - POSTGRES_DB=portfolio

volumes:
  postgres_data: