name: 'porfolio'

services:
  app:
    platform: linux/amd64
    build: .
    restart: always
    volumes:
      - .:/src/app
    ports:
      - 9001:5000
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=usman
      - POSTGRES_PASSWORD='Babalogun#1'
      - POSTGRES_DB=portfolio

volumes:
  postgres_data:
